name: Trigger Cloudflare Deployment

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Cloudflare Deployment
      run: |
        curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/384e35fb-982c-400b-833a-d2c2bb6004e6
